### ISSUE TITLE
this.content is undefined

### ISSUE THREAD

**Issue by PAT-Development** [bradmartin/nativescript-pulltorefresh#8]
I have tried to use the current version of nativescript-pulltorefresh with the helloworld-ng template. While compiling the typescript I get the `Cannot find name 'UIRefreshControl'` error, but I let the compiler ignore it. But during the runtime, I get following error:
`TypeError: undefined is not an object (evaluating 'this.content.ios')
	ORIGINAL STACKTRACE:
	onLoaded@file:///app/tns_modules/nativescript-pulltorefresh/pulltorefresh.js:60:25`
It seems, that it comes from this part of pulltorefresh.ios.ts: 
```
if (this.content.ios instanceof UIScrollView) {
    // Ensure that we can trigger the refresh, even if the content is not large enough
    this.content.ios.alwaysBounceVertical = true;
            
    this.content.ios.addSubview(this._refreshControl);
}
```

This is my [app.component.ts](http://pastebin.com/espJZPxU).

If I wrap it into `if(this.content != undefined) { [...] }`, the runtime error is solved, but I get only the list view..

Thanks in advance!

EDIT:
If I change the line in app.component.ts to:
`registerElement("PullToRefresh", require('nativescript-pulltorefresh').PullToRefresh);`
I get `TypeError: undefined is not a constructor (evaluating 'new viewClass()')`

**Comment by bradmartin** [comment]
@peterstaev do you know how to fix this?

**Comment by PeterStaev** [comment]
@bradmartin  seems something related to Angular, since the demo app is working fine with {N} 2.0. And my knowledge with Angular is zero, so have no idea :(

**Comment by bradmartin** [comment]
@NathanWalker - does this sound like an Angular2 issue?

**Comment by NathanWalker** [comment]
It does sound like it. Would need to investigate this week, will try to do that.

**Comment by bradmartin** [comment]
Thanks man. Not sharp enough on ng2 yet

**Comment by matt4446** [comment]
@PAT-Development 
Just for fun... can you try adding a [scrollview in there](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/controls/pullToRefresh/pullToRefresh.control.ts#L15-l19). 
I will try it with a `ListView` one day to test, but not today.

**Comment by PAT-Development** [comment]
Same error. Is my `registerElement("PullToRefresh", () => { return require('nativescript-pulltorefresh').PullToRefresh });` correct? I couldn't see one in your file. If I leave it out, no error messages appear, but no pushtorefresh-view is loaded.

**Comment by matt4446** [comment]
I have this hiding somewhere [else](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/app.ts#L91-108) add [here](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/decorators/app.ts#L60-66), but that's not very significant (and doesnt work in ios i hear, so ignore my code for that):

The registration is required and pretty much replaces the namespace part of the xaml such that 

This would be correct based on my copying and pasting from both parts above:  
```js
registerElement("PullToRefresh", () => require("nativescript-pulltorefresh").PullToRefresh);
```
The element would become: 
```xml
<PullToRefresh></PullToRefresh>
``` 
and can be seen to be equal to 

```xml
<page xmlns="http://schemas.nativescript.org/tns.xsd"
      xmlns:PullRefresh="nativescript-pulltorefresh"
      loaded="pageLoaded">
    <stack-layout>   
        <PullRefresh:PullToRefresh refresh="refreshList">
        etc 
```

```js 
registerElement("PullToRefresh", () => require("nativescript-pulltorefresh").PullToRefresh);
```

The name is not too important but `require("nativescript-pulltorefresh").PullToRefresh)` is critical.  

```js
registerElement("RefreshContent", () => require("nativescript-pulltorefresh").PullToRefresh);
```
would become
```xml
<RefreshContent></RefreshContent>
```

Can you check if it runs in the android emulator? 

I need to get telerik appbuilder CLI to work for my IOS version and had not planned on doing that for a while. But I need to dig a bit deeper into the pullToRefresh anyway so will probably be making a standalone demo.

**Comment by matt4446** [comment]
```js
registerElement("PullToRefresh", () => require("nativescript-pulltorefresh").PullToRefresh);
``` 
Will hopefully fix your problem. I skipped that in my demo and found it breaks with just `require("nativescript-pulltorefresh").PullToRefresh)`.

Here is my new [sample page](https://github.com/matt4446/Demo-Material-NativeScript/blob/master/app/controls/pullToRefresh.component.ts) or more simply on the [page](https://github.com/matt4446/Demo-Material-NativeScript/blob/master/app/pages/vanilla.pullToRefresh.component.ts)

https://github.com/matt4446/Demo-Material-NativeScript has cardview and pull to refresh examples in nativescript + angular rc1.

I have not been able to run it with ios yet so no guarantee.

**Comment by PAT-Development** [comment]
Unfortunately not.. But your demo is working on iOS. I try to find the differences in the implementations!

**Comment by PAT-Development** [comment]
The issue is a bit different than we thought. I found out that it's working if the component is loaded on a subpage over routing. Without routing the same component fails.

**Comment by matt4446** [comment]
Could be based on the [loaded](https://github.com/NativeScript/nativescript-angular/issues/259)event bug currently floating about.

**Comment by bradmartin** [comment]
Anything new here, I'm going to close and just comment if it needs to be reopened.

**Comment by davidsandoz** [comment]
I am facing the same issue with a NativeScript 3.2.0 + Angular 4.2.6 project.
```
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating 'this.content.ios')
CONSOLE ERROR [native code]: ERROR CONTEXT [object Object]
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:165:30: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
CONSOLE ERROR file:///app/tns_modules/tns-core-modules/trace/trace.js:165:30: ns-renderer: undefined is not an object (evaluating 'this.content.ios')
```

An additional information that could be useful is this `ERROR BOOTSTRAPPING ANGULAR`.

In pulltorefresh.ios.ts, I tried to replace `this.content.ios`  with `topmost().currentPage.content.ios`, which requires to `import {topmost} from 'ui/frame';`.

With that change, I don't get the `undefined` error anymore, but the "Content must inherit from UIScrollView!" error.

I checked the constructor name of `topmost().currentPage.content.ios` and it's a UIView. I guess I'm not getting the correct element. But maybe this could help figuring out a proper solution.

**Comment by davidsandoz** [comment]
I'll just mention you here @bradmartin, in case you didn't get notified of my last message because the issue is closed.

**Comment by davidsandoz** [comment]
@bradmartin Would you have any hint on what we could do to make it work?

Here some more information on my usage of the plugin:

I'm doing the following before `@Component`:
```
import {registerElement} from 'nativescript-angular/element-registry';
registerElement('PullToRefresh', () => require('nativescript-pulltorefresh').PullToRefresh);
```

And in the template I have:
```
<PullToRefresh (refresh)="refreshList($event)">
    <WebView #appWebView [src]="webViewSrc"></WebView>
</PullToRefresh>
```

Note that this works very well on Android.

**Comment by san18793** [comment]
Guys anyone solved this issue ? If yes kindly update it . I am getting the same above mentioned error and don't know what to do.

**Comment by dmyers** [comment]
> Guys anyone solved this issue ? If yes kindly update it . I am getting the same above mentioned error and don't know what to do.

Not sure if it helps, but I wrapped `<PullToRefresh>` in a `<StackLayout>` and it fixed the issue for me using NS Vue.
